# Generated by Django 5.1.3 on 2024-11-22 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='compl_loc',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='document',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='compl_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 1, 4, 20, 149714)),
        ),
    ]
