# Generated by Django 5.1.3 on 2024-11-25 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0003_complaint_user_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='compl_loc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='desc',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='document',
            field=models.FileField(default='No description', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 20, 30, 27, 280380)),
        ),
    ]
