# Generated by Django 5.1.3 on 2024-12-28 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0007_rename_description_event_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 23, 28, 20, 872539)),
        ),
    ]
