# Generated by Django 5.1.3 on 2024-12-30 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0010_transaction_alter_death_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 23, 55, 37, 263982)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete')], max_length=15),
        ),
    ]
