# Generated by Django 5.1.3 on 2024-12-30 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0011_alter_death_date_of_issue_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 0, 4, 43, 567537)),
        ),
    ]
