# Generated by Django 5.1.3 on 2024-12-30 19:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now  # Use timezone.now for dynamic defaults


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0012_alter_death_date_of_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='send',
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_date',
            field=models.DateField(default=now),  # Fixed to use a callable
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=now),  # Fixed to use a callable
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
