# Generated by Django 5.1.3 on 2024-12-30 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0013_remove_transaction_send_transaction_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 0, 37, 19, 64333)),
        ),
    ]
