# Generated by Django 5.1.3 on 2024-12-30 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0015_alter_death_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 0, 45, 17, 472329)),
        ),
    ]
