# Generated by Django 5.1.3 on 2024-12-30 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0017_alter_death_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 0, 55, 26, 971349)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
