# Generated by Django 5.1.3 on 2024-12-30 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0020_alter_death_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 1, 4, 43, 163667)),
        ),
    ]
