# Generated by Django 5.1.3 on 2025-02-06 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0025_transaction_user_alter_death_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 15, 52, 25, 617200)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
