# Generated by Django 5.1.3 on 2025-02-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0026_alter_death_date_of_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 18, 51, 36, 473536)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
