# Generated by Django 5.1.3 on 2025-02-06 14:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0027_remove_transaction_user_transaction_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 19, 31, 54, 190350)),
        ),
    ]
