# Generated by Django 5.1.3 on 2025-02-07 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0028_transaction_upload_date_alter_death_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 10, 5, 15, 840889)),
        ),
    ]
