# Generated by Django 5.1.3 on 2025-03-20 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0032_birthcertificate_alter_death_date_of_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='panchayat_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 7, 45, 21, 402422)),
        ),
    ]
