# Generated by Django 5.1.3 on 2025-03-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0038_alter_death_date_of_issue_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 22, 0, 51, 327794)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
