# Generated by Django 5.2 on 2025-04-06 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egramApp', '0047_emergencycontact_healthcenter_healthcomplaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillagePopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.IntegerField()),
                ('male_population', models.IntegerField()),
                ('female_population', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='HealthCenter',
        ),
        migrations.DeleteModel(
            name='HealthComplaint',
        ),
        migrations.DeleteModel(
            name='HealthPost',
        ),
        migrations.DeleteModel(
            name='MedicalCamp',
        ),
        migrations.AlterField(
            model_name='death',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 0, 27, 12, 214518)),
        ),
    ]
